-- Migration: add the LinkedIn URL queue to an existing database.
-- (schema.sql already includes this for fresh setups.)

create table if not exists public.linkedin_queue (
  id           bigint generated by default as identity primary key,
  url          text not null,
  status       text default 'pending',   -- pending | processing | done | error
  error        text,
  job_id       text,
  created_at   timestamptz default now(),
  processed_at timestamptz
);

create index if not exists linkedin_queue_status_idx on public.linkedin_queue (status);

alter table public.linkedin_queue enable row level security;

do $$ begin
  create policy "public read queue"  on public.linkedin_queue for select using (true);
  create policy "public write queue" on public.linkedin_queue for all    using (true) with check (true);
exception when duplicate_object then null; end $$;
