-- JobIntel — Supabase schema
-- Run this in the Supabase SQL Editor (or `supabase db push`).

create table if not exists public.companies (
  id         text primary key,
  name       text not null,
  url        text,
  ats        text,            -- greenhouse | lever | ashby | smartrecruiters | company
  slug       text,            -- board identifier used by the connector
  industry   text,
  country    text,
  status     text default 'active',
  frequency  text default 'daily',
  created_at timestamptz default now()
);

create table if not exists public.jobs (
  job_id          text primary key,
  company_id      text references public.companies(id) on delete cascade,
  title           text,
  company         text,
  location        text,
  country         text,
  remote          text,
  employment_type text,
  department      text,
  seniority       text,
  salary          text,
  salary_min      integer,
  salary_max      integer,
  skills          text[],
  description     text,
  apply_url       text,
  linkedin_url    text,
  source          text,        -- ATS the job came from
  posted_date     text,        -- ISO yyyy-mm-dd (text keeps empty values safe)
  updated_at      timestamptz default now(),
  -- AI enrichment (populated by `npm run enrich`)
  required_skills text[],
  tech_stack      text[],
  experience_min  integer,
  experience_max  integer,
  ai_seniority    text,
  job_category    text,
  ai_summary      text,
  enriched_at     timestamptz
);

create index if not exists jobs_company_idx  on public.jobs (company_id);
create index if not exists jobs_source_idx   on public.jobs (source);
create index if not exists jobs_posted_idx   on public.jobs (posted_date desc);
create index if not exists jobs_department_idx on public.jobs (department);
create index if not exists jobs_category_idx   on public.jobs (job_category);

-- Queue of user-submitted LinkedIn job URLs to parse (drained by `npm run linkedin`).
create table if not exists public.linkedin_queue (
  id           bigint generated by default as identity primary key,
  url          text not null,
  status       text default 'pending',   -- pending | processing | done | error
  error        text,
  job_id       text,
  created_at   timestamptz default now(),
  processed_at timestamptz
);

create index if not exists linkedin_queue_status_idx on public.linkedin_queue (status);

-- Learned scraping adapters (auto-discovery connector), cached per domain.
create table if not exists public.adapters (
  domain     text primary key,
  spec       jsonb not null,
  created_at timestamptz default now()
);

-- Row Level Security.
-- The crawler writes with the service_role key (bypasses RLS).
-- These policies make the dashboard usable WITHOUT auth (internal/demo use).
-- For production, replace the anon write policies with authenticated checks.
alter table public.companies enable row level security;
alter table public.jobs enable row level security;
alter table public.linkedin_queue enable row level security;
alter table public.adapters enable row level security;

do $$ begin
  create policy "public read companies"  on public.companies for select using (true);
  create policy "public write companies" on public.companies for all    using (true) with check (true);
  create policy "public read jobs"       on public.jobs      for select using (true);
  create policy "public write jobs"      on public.jobs      for all    using (true) with check (true);
  create policy "public read queue"      on public.linkedin_queue for select using (true);
  create policy "public write queue"     on public.linkedin_queue for all    using (true) with check (true);
  create policy "public read adapters"   on public.adapters  for select using (true);
  create policy "public write adapters"  on public.adapters  for all    using (true) with check (true);
exception when duplicate_object then null; end $$;
